# name: 'Sync S3'

# concurrency:
#   group: prod_deploy
#   cancel-in-progress: false

# on:
#   repository_dispatch:
#   workflow_dispatch:
#   push:
#     branches:
#       - mn-test-enables-template-lambda

# jobs:
#   deploy:
#     name: 'Sync'
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           # aws-region: us-east-1

#       - uses: badsyntax/github-action-aws-s3@v0.0.1
#         name: Sync HTML files to S3
#         id: sync-html-s3
#         with:
#           bucket: 'lambda-test-s3-bucket-template'
#           # # aws-region: 'us-east-1'
#           # action: 'sync' # sync|clean
#           # src-dir: './out' # required only if action is sync
#           # # # files-glob: '**/*.html' # required only if action is sync
#           # prefix: 'preview'
#           # sync-strategy: |
#           #   ETag
#           #   Content-Type
#           #   Cache-Control
#           # strip-extension-glob: '**/**.html'
#           # cache-control: 'public,max-age=0,s-maxage=31536000,must-revalidate'

#       - name: Output Synced Files
#         run: |
#           echo "Synced object keys: $S3SyncedFiles"
#         env:
#           # Use outputs from previous sync steps
#           S3SyncedFiles: ${{ steps.sync-html-s3.outputs.modified-keys }}

name: Upload lambda

on:
  push:
    branches:
    - mn-test-enables-template-lambda

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        # SOURCE_DIR: 'public'      # optional: defaults to entire repository