# name: 'Sync S3'

# concurrency:
#   group: prod_deploy
#   cancel-in-progress: false

# on:
#   repository_dispatch:
#   workflow_dispatch:
#   push:
#     branches:
#       - mn-test-enables-template-lambda

# jobs:
#   deploy:
#     name: 'Sync'
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           # aws-region: us-east-1

#       - uses: badsyntax/github-action-aws-s3@v0.0.1
#         name: Sync HTML files to S3
#         id: sync-html-s3
#         with:
#           bucket: 'lambda-test-s3-bucket-template'
#           # # aws-region: 'us-east-1'
#           # action: 'sync' # sync|clean
#           # src-dir: './out' # required only if action is sync
#           # # # files-glob: '**/*.html' # required only if action is sync
#           # prefix: 'preview'
#           # sync-strategy: |
#           #   ETag
#           #   Content-Type
#           #   Cache-Control
#           # strip-extension-glob: '**/**.html'
#           # cache-control: 'public,max-age=0,s-maxage=31536000,must-revalidate'

#       - name: Output Synced Files
#         run: |
#           echo "Synced object keys: $S3SyncedFiles"
#         env:
#           # Use outputs from previous sync steps
#           S3SyncedFiles: ${{ steps.sync-html-s3.outputs.modified-keys }}



on:
  push:
    branches:
    - mn-test-enables-template-lambda

steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0   # Required
   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ always() }} # This ensures that your workflow runs successfully
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Amazon CodeGuru Reviewer Scanner
      uses: aws-actions/codeguru-reviewer@v1.1
      if: ${{ always() }} 
      with:
        build_path: build # build artifact(s) directory
        s3_bucket: lambda-test-s3-bucket-template  # S3 Bucket with "codeguru-reviewer-*" prefix
    
    - name: Upload review result
      if: ${{ github.event_name != 'push' }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json