name: upload lambda template

on:
  push:
    branches:
    - mn-test-enables-template-lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@mn-test-enables-template-lambda
    - uses: nayebare/github-test-lambda-aws@mn-test-enables-template-lambda
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository