# name: upload lambda template

# on:
#   push:
#     branches:
#     - mn-test-enables-template-lambda

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     # - uses: actions/checkout@mn-test-enables-template-lambda
#     - uses: nayebare/github-test-lambda-aws@mn-test-enables-template-lambda
#       with:
#         args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
#         SOURCE_DIR: 'public'      # optional: defaults to entire repository


name: Build & deploy

on:
  push:
    branches:
      - mn-test-enables-template-lambda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key:${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        run: aws s3 sync ./YOUR-BUILD-DIR s3://YOUR-BUCKET-NAME